### ISSUE TITLE
How to print a character with`write!()`, after acquiring it with `Stdin::keys()` 

### ISSUE THREAD

**Issue by WarpspeedSCP** [ticki/termion#132]
I looked at the examples, but they only show the use of `println!()` to print the character (the keys example).

How do I extract the character from it so I can use it with `write!()`?

It prints well enough with `println!()`, but if I pass it to `write!()`, it complains about the unimplemented `termion::event::Key: std::fmt::Display` trait. I also wish to store the character in a `String`, and the method to do either is not really apparent.

**Comment by IGI-111** [comment]
You'll have to destructure the `Key` to get the underlying character if you want to display it. Or just use the Debug trait.

**Comment by WarpspeedSCP** [comment]
Well, I managed it somehow within the match block, but I don't understand how the Key struct is converted into a char inside there. It just seems too much like magic to me. Can you explain how it works, please?

**Comment by WarpspeedSCP** [comment]
Does `Key::Char()` return the character?

**Comment by IGI-111** [comment]
[The Rust Book](https://doc.rust-lang.org/1.2.0/book/match.html)'s sections on `match` and pattern matching do it better than I ever could. You might want to read more into [ pattern matching itself](https://en.wikipedia.org/wiki/Pattern_matching) as well.

Though do close the issue please since this isn't a library problem.
